name: Send Email on Push

on:
  push:
    branches:
      - main  

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Отправка email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com      
          server_port: 465                     
          username: ${{ secrets.MSMASHA_USERNAME }} 
          password: ${{ secrets.MSMASHA_PASSWORD }} 
          subject: GitHub Push Notification
          body: "Произошел push в репозиторий!"
          to: marijagorbu228@gmail.com            
          from: ${{ secrets.EMAIL_USER }}      
